# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0002_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
            ],
        ),
    ]
