# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
