# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0004_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('engine', models.CharField(choices=[('ODBC', 'ODBC'), ('MYSQL', 'PyMySQL')], max_length=255)),
                ('connection_string', models.TextField()),
                ('server', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('encoding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webquery.Encoding')),
            ],
        ),
    ]
