# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0006_auto_20170617_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='database',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connection',
            name='server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connection',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
